# Tuple

t=(2,3,6,5,4,9,7,1,8)
print("Tuple:",t)
print("Length of tuple:",len(t))
print("first element of tuple is:",t[0])
print("last element of tuple is:",t[-1])
print("slicing of tuple:",t[0:5])
print("tuple after concatenation:",t+(10,11,12))
print("tuple repetition:",t*2)
print("tuple after deletion:",t[1:5])
print("tuple after sorting:",sorted(t))
print("tuple after reversing:",t[::-1])
print("tuple after max:",max(t))
print("tuple after min:",min(t))
print("tuple after sum:",sum(t))
print("tuple after count:",t.count(2))
print("tuple after index:",t.index(5))
print("tuple after membership:",2 in t)
print("tuple after membership:",10 not in t)
print("tuple after membership:",t[0] in t)
print("tuple after membership:",t[0] not in t)
print("tuple after membership:",t[0] in t and t[1:5] in t)
