# set

flower = {"rose", "lily", "jasmine", "sunflower", "tuple", "daisy", "cherry"}
fruite = {"apple", "banana", "cherry", "orange", "kivi", "melon","mango"}
print(flower)
print(fruite)
fruite.add("grapes")
fruite.remove("banana")
flower.discard("tuple")
flower.update(["lotus", "hibiscus"])
print()
print("union operation on sets")
print("intersection operation on sets")
print(flower&fruite)
print("difference operation on sets")
print(flower-fruite)
print("symmetric difference operation on sets")
print(flower^fruite)
print("subset operation on sets")
print(flower.issubset(fruite))
print("superset operation on sets")
print(flower.issuperset(fruite))
print("disjoint operation on sets")
print(flower.isdisjoint(fruite))
print("length of flower set is:",len(flower))
print("length of fruite set is:",len(fruite))
print("maximum element in flower set is:",max(flower))
print("maximum element in fruite set is:",max(fruite))
print("minimum element in flower set is:",min(flower))
print("minimum element in fruite set is:",min(fruite))
print("sorted flower set is:",sorted(flower))
print("sorted fruite set is:",sorted(fruite))
print("clear operation on sets")
flower.clear()
fruite.clear()
# set

flower = {"rose", "lily", "jasmine", "sunflower", "tuple", "daisy", "cherry"}
fruite = {"apple", "banana", "cherry", "orange", "kivi", "melon","mango"}
print(flower)
print(fruite)
fruite.add("grapes")
fruite.remove("banana")
flower.discard("tuple")
flower.update(["lotus", "hibiscus"])
print()
print("union operation on sets")
print("intersection operation on sets")
print(flower&fruite)
print("difference operation on sets")
print(flower-fruite)
print("symmetric difference operation on sets")
print(flower^fruite)
print("subset operation on sets")
print(flower.issubset(fruite))
print("superset operation on sets")
print(flower.issuperset(fruite))
print("disjoint operation on sets")
print(flower.isdisjoint(fruite))
print("length of flower set is:",len(flower))
print("length of fruite set is:",len(fruite))
print("maximum element in flower set is:",max(flower))
print("maximum element in fruite set is:",max(fruite))
print("minimum element in flower set is:",min(flower))
print("minimum element in fruite set is:",min(fruite))
print("sorted flower set is:",sorted(flower))
print("sorted fruite set is:",sorted(fruite))
print("clear operation on sets")
flower.clear()
fruite.clear()